language: groovy
jdk:
  - openjdk6
  - oraclejdk7
branches:
  only:
    - master
script: ./grailsw refresh-dependencies
     && ./grailsw package-plugin
     && cd test/projects/default22
     && ./grailsw refresh-dependencies
     && ./grailsw "test-app functional:"
